### ISSUE TITLE
Create reservation

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#104]
As a guest I want to create a reservation by entering date and time and number of adults and kids.

**Acceptance criteria**
1. only date and time in future possible and both required
2. only valid email addresses: text@text.xx, one entered email-address is required
3. if AGB are not checked, an error message is shown
4. after the reservation is done
- I see a confirmation screen of my reservation with date-time, number of persons and kids
- I receive a confirmation email about my reservation

**Wireframes**
see current demo

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
