### ISSUE TITLE
Handle invite

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#105]
As an invited guest I would like to receive an email - after somebody as invited me - with the option to accept or decline the invite so that the system knows about my participation.

**Acceptance Criteria**
1. the mail contains the following information about the invite
- who has invited
- who else is invited
- date and time of the invite
- button to accept or decline
2. after pressing the buttons the system will store the status (yes/no) of my invite

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
