### ISSUE TITLE
Revoke accepted invite

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#106]
As an invited guest I would like to revoke my previous answer in order to inform the system and the inviter about my no show.

**Acceptance Criteria**
1. the inviter and myself receives an email about my cancellation
2. the system sets my status of my invite to no
3. in case I have placed an order, the order is also removed from the system.
4. the cancellation is only possible 10 minutes before the event takes place. The system shows a message that cancellation is not possible anymore if the cancellation is attempted closer to the event than 10 minutes.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
