### ISSUE TITLE
Calculate best table

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#107]
As a guest I would like the system to check (1 hour before my invite) all my invites and to reserve a table fitting the number of accepted users.

**Details**
Pseudo-algorithm for reservation: 
1. Find table for given date and time where seats of guests >= Count of invited guests plus one. 
1a. In case no results, decline request and show error message to user. 
1b. In case of any result, make a reservation for table. 
2. For each decline of a guest remove guest and search with reduced number for new table. 
2a. In case table is found, reserve it and remove reservation from previous table. 
2b. In case not, do not change reservations.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
