### ISSUE TITLE
Find table by reservation info

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#108]
As a waiter I would like to search by reference number or email address for the reserved table in order to know the table for my visit. (when arriving at the restaurant)

**Acceptance Criteria**
1. After entering the email or reference number the systems shows the number of the table. In case no reservation found, a message is shown.
2. Entered email address could be email of inviter or any invited guest.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.

**Comment by Dawid-Dlugokecki-Capgemini** [comment]
@jmsanmu please do NOT close these user stories. They are used in a current project to update the my thai star implementation. Please get in touch BEFORE closing user stories.

**Comment by jmsanmu** [comment]
@Dawid-Dlugokecki-Capgemini Thank you for the info. Before to submit a My Thai Star issue in this cross platform framework I would appreciate you to put the issues in the correct repository (https://github.com/devonfw/my-thai-star). If you are working in another project using devon4net I would suggest you to use another git project or even the My Thai Star repository. Kind regards

**Comment by jmsanmu** [comment]
No more information. Proceed to close
