### ISSUE TITLE
Cancel invite

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#109]
As a guests who has sent an invite I want to be able to cancel my previous invite in order to inform the restaurant and my invited guests that I will not show up

**Acceptance Criteria**
1. the option to cancel the invite is available in the confirmation-mail about my invite
2. after my cancellation all invited guests receives a mail about the cancellation
3. I see a confirmation that my invite was canceled successfully
4. after my cancellation my invite and reservation and all orders related to it are deleted from the system and no one can accept or decline any invite for it
5. the cancellation is only possible one hour before the invite takes place. After that I am not allowed to cancel it any more.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.

**Comment by Dawid-Dlugokecki-Capgemini** [comment]
@jmsanmu please do NOT close these user stories. They are used in a current project to update the my thai star implementation. Please get in touch BEFORE closing user stories.

**Comment by jmsanmu** [comment]
@Dawid-Dlugokecki-Capgemini Thank you for the info. Before to submit a My Thai Star issue in this cross platform framework I would appreciate you to put the issues in the correct repository (https://github.com/devonfw/my-thai-star). If you are working in another project using devon4net I would suggest you to use another git project or even the My Thai Star repository. Kind regards

**Comment by jmsanmu** [comment]
No more information. Proceed to close
