### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Dawid-Dlugokecki-Capgemini** [devonfw/devon4net#110]
As a guest I want to have a user profile to associate it with my twitter account to be able to like/rate dishes

**Acceptance Criteria**
1. Username of my profile is my email address
2. My profile is protected by password
3. I can log in and log out to my profile
4. I can reset my password by triggering the reset by mail
5. I can associate my profile with my twitter account in order to rate dishes and store my favorites by liking posts associated to dishes

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.

**Comment by Dawid-Dlugokecki-Capgemini** [comment]
> 

@jmsanmu please do NOT close these user stories. They are used in a current project to update the my thai star implementation. Please get in touch BEFORE closing user stories.

**Comment by jmsanmu** [comment]
@Dawid-Dlugokecki-Capgemini Thank you for the info. Before to submit a My Thai Star issue in this cross plataform framework I would apreciate you to put the issues in the correct repository (https://github.com/devonfw/my-thai-star). If you are working in another project using devon4net I would suggest you to use another git project or even the My Thai Star repository. Kind regards

**Comment by jmsanmu** [comment]
No more information. Proceed to close
