### ISSUE TITLE
See all orders/reservations

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#111]
As a waiter I want to see all orders/reservation in order to know what is going on in my restaurant

Acceptance criteria:
1. all orders/reservations are shown in a list view (read-only). Those list can be filtered and sorted (similar to excel-data-filters)
2. orders/reservations are shown in separate lists.
3. for each order the dish, meat, comment, item, reservation-id, reservation date-time, creation-date-time is shown
4. for each reservation the inviters email, the guests-emails, the number of accepts and declines, calculated table number, the reservation-id, reservation date-time and creation-date-time are shown
5. the default filter for all lists is the today’s date for reservation date-time. this filter can be deleted.
6. only reservations and orders with reservation date in the future shall be available in this view. All other orders and reservation shall not be deleted; for data Analytics those orders and reservation shall still exist in the system.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
