### ISSUE TITLE
Rate your dish

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#112]
As a guest I want to add a comment or a like via my twitter account for a dish

Acceptance criteria:
1. Before I write my rate I would like to be able to read all tweets of other users for this dish
2. I would like to see the number of likes for a dish

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
