### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#114]
As a guest I want to cancel my order.

Acceptance criteria:
1. in my received confirmation mail I have the option to cancel my order
2. the cancellation is only possible one hour before my reservation takes place
3. my order is deleted from the system

Remark: Changing the order is not possible. For that the order must be canceled and created from scratch again

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
