### ISSUE TITLE
Define Order

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#115]
As a guest I want to define my order by selecting dishes from the menu

Acceptance criteria:
1. The guest can add each dish to the order
2. In case the guest adds the same dish multiple times, a counter in the order for this dish is increased for this dish
3. The guest can remove the dish from the order
4. The guest can add for each main dish the type of meat (pork, chicken, tofu)
5. The guest can add for each dish a free-text-comment
6. After adding/removing any dish the price is calculated including VAT

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
