### ISSUE TITLE
Filter Menu

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#116]
As a guest I want to filter the menu so that I only see the dishes I am interested in

Acceptance Criteria:

1. The guest can filter by
- type: starter | main dish | dessert; if nothing is selected all are shown (default value)
- veggie (yes|no|does not matter (default))
- vegan (yes|no|does not matter (default))
- rice (yes|no|does not matter (default))
- curry (yes|no|does not matter (default))
- noodle (yes|no|does not matter (default))
- price (range)
- ratings (range)
- my favorite (yes|no|does not matter (default)) — free text (search in title and description)
2. The guest can sort by price asc, rating asc
3. After setting the filter, only dishes are shown which fulfill those criteria
4. By pressing the button reset filter all filter are reset to the initial value
5. By pressing the filter button the filter is applied

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
