### ISSUE TITLE
Read Twitter rating for Dishes

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#117]
As a guest I want to read for all dishes the rating done be twitter because I would like to know the opinion of others

Acceptance criteria:
1. For each dish I see the latest 3 comments done by twitter for this vote (text, username, avatar)
2. For each dish I see the number of likes done by twitter

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
