### ISSUE TITLE
Order the Order

### ISSUE THREAD

**Issue by AlexanderTrusheim** [devonfw/devon4net#118]
As a guest I want to order my selected dishes (order)

Acceptance criteria:

1. I receive a mail containing my order with all dishes and the final price
   - precondition for ordering:
     - Each order must be associated with a reservation / invite. Without any reference no order could be placed. The reference could be obtained from a previous reservation/invite (created during same session) or by the previous accepted invite (link in email) or by entering the reference id when asked by the system.
       - In case precondition is not fulfilled, the guest is asked
         a. whether he/she would like to create a reservation/invite and is forwarded to US Invite Friends. Only after finalizing the reservation the order is accepted.
         b. or he/she would enter previous created reservation-id he/she knows in order to associate his/her order with this reservation

**Comment by jmsanmu** [comment]
Thank you @AlexanderTrusheim , but in this repository there is no My Thai Star implementation. The implementation of My Thai Star was done when My Thai Star was born years ago. Also, It was removed and not supported since the .net core 2.1 version. Kind regards.
